In [1]:
from executor import QuantumCircuit, QuantumOperator

from qiskit.circuit import ParameterVector

from executor.qulacs import QulacsCircuit, QulacsObservable

x = ParameterVector('x',1)
p = ParameterVector('p',2)

qc = QuantumCircuit(2)
qc.h(0)
qc.cry(0, 1, p[0]*x[0])
qc.crx(1, 0, p[1]*x[0])

In [2]:
qulacs = QulacsCircuit(qc)

print("qulacs.circuit_arguments",qulacs.circuit_arguments)

qulacs._operation_list

qulacs.circuit_arguments {'p': 2, 'x': 1}


['h',
 'ry',
 'cx',
 'ry',
 'cx',
 'rz',
 'cx',
 'rz',
 'rx',
 'rz',
 'rx',
 'rz',
 'cx',
 'rz',
 'rx',
 'rz',
 'rx',
 'rz']

In [3]:
pop = ParameterVector('pop',2)
operator = QuantumOperator(["ZI","II"],[pop[0],pop[1]])
operator2 = QuantumOperator(["XI","IX"],[pop[0],pop[1]])

In [4]:
from executor.qulacs.qulacs_executor import QulacsExecutor



executor = QulacsExecutor(seed=0, shots=10000)

executor.expectation_value(
    qc,
    operator,
    p = [0.3,0.5],
    x = 0.1,
    pop = [0.5, 0.6]
)


1.099887508437248

In [5]:
executor.statevector(
    qc,
    p = [0.3,0.5],
    x = 0.1,
    pop = [0.5, 0.6]
)

array([7.07106781e-01+2.44249065e-15j, 7.07027233e-01+2.05391260e-15j,
       3.52365706e-19-2.65127480e-04j, 1.06028897e-02+1.73472348e-18j])

In [6]:
executor.sample(
    qc,
    pop = [0.5, 0.6],
    p = [0.3,0.5],
    x = 0.1,
)



{'01': 5008, '00': 4990, '11': 2}

In [7]:
executor.sample(
    qc,
    x = [0.8],
    p = [0.3,0.5],
)


{'01': 4977, '00': 4943, '11': 76, '10': 4}

In [8]:
v = executor.expectation_value_derivatives(
    qc,
    operator,
    "pop",
    "p",
    "",
    "x",
    pop = [0.5, 0.6],
    p = [0.3,0.5],
    x = 0.1,
    )
print(v)

{'expectation_value': 1.099887508437248, 'p': array([-7.49887505e-04, -5.55114484e-18]), 'pop': array([0.99977502, 1.        ]), 'x': array([-0.00224966])}


In [9]:
from executor.pennylane.pennylane_circuit import PennyLaneCircuit

pennylane_circuit = PennyLaneCircuit(qc)

pennylane_circuit.parameter_names

pennylane_circuit.build_pennylane_circuit()

<function executor.pennylane.pennylane_circuit.PennyLaneCircuit.build_pennylane_circuit.<locals>.pennylane_circuit(*args)>

In [10]:
from executor.pennylane.pennylane_observable import PennyLaneObservable

pennylane_obs = PennyLaneObservable(operator)

pennylane_obs.parameter_names

pennylane_obs.build_pennylane_observable()

<function executor.pennylane.pennylane_observable.PennyLaneObservable.build_pennylane_observable.<locals>.pennylane_observable(*args)>

In [11]:
from executor.pennylane.pennylane_executor import PennylaneExecutor



executor = PennylaneExecutor(shots=10000, seed=0)



executor.expectation_value(
    qc,
    operator,
    p = [0.3,0.5],
    x = 0.1,
    pop = [0.5, 0.6]
)

1.0998875084372473

In [12]:
executor.statevector(
    qc,
    p = [0.3,0.5],
    x = 0.1,
    pop = [0.5, 0.6]
)

array([ 7.07106781e-01+0.00000000e+00j,  7.07027233e-01+0.00000000e+00j,
       -1.62343760e-20-2.65127480e-04j,  1.06028897e-02+9.63082522e-35j])

In [13]:
executor.sample(
    qc,
    p = [0.3,0.5],
    x = 0.1,
    pop = [0.5, 0.6]
)


[{'01': 5008, '00': 4990, '11': 2}]

In [14]:
v = executor.expectation_value_derivatives(
    qc,
    operator,
    "pop",
    "pop[0]",
    "p",
    "",
    "x",
    ("p[0]","p[0]"),
    ("p","x"),
    pop = [0.5, 0.6],
    p = [0.3,0.5],
    x = 0.1,
    )
print(v)

{'expectation_value': array(1.09988751), ('p', 'x'): array([[-1.49955003e-02],
       [-5.20413674e-18]]), ('p[0]', 'p[0]'): -0.00249887508437247, 'p': array([-7.49887505e-04, -3.46944695e-19]), 'pop': array([0.99977502, 1.        ]), 'pop[0]': 0.9997750168744941, 'x': array([-0.00224966])}


c:\Users\DKR\Documents\Git Repositories\executor\.venv\lib\site-packages\autograd\numpy\numpy_vjps.py:943: ComplexWarning: Casting complex values to real discards the imaginary part
  onp.add.at(A, idx, x)
c:\Users\DKR\Documents\Git Repositories\executor\.venv\lib\site-packages\autograd\numpy\numpy_vjps.py:943: ComplexWarning: Casting complex values to real discards the imaginary part
  onp.add.at(A, idx, x)
c:\Users\DKR\Documents\Git Repositories\executor\.venv\lib\site-packages\autograd\numpy\numpy_vjps.py:943: ComplexWarning: Casting complex values to real discards the imaginary part
  onp.add.at(A, idx, x)
c:\Users\DKR\Documents\Git Repositories\executor\.venv\lib\site-packages\autograd\numpy\numpy_vjps.py:943: ComplexWarning: Casting complex values to real discards the imaginary part
  onp.add.at(A, idx, x)


In [ ]:
from executor.qiskit.qiskit_executor import QiskitExecutor
from executor.qiskit import QiskitCircuit

qiskit = QiskitCircuit(qc)
executor = QiskitExecutor(seed=0, shots=10000)

executor.expectation_value(
    qc,
    operator,
    p = [0.3,0.5],
    x = 0.1,
    pop = [0.5, 0.6]
)

c:\Users\MOW-DK\dev\Executor\.venv\Lib\site-packages\qiskit\primitives\backend_estimator_v2.py:290: ComplexWarning: Casting complex values to real discards the imaginary part
  evs[index] += expval * coeff


np.float64(1.099755859375)

In [4]:
executor.statevector(
    qc,
    p = [0.3,0.5],
    x = 0.1,
    pop = [0.5, 0.6]
)

array([0.70710678+0.j        , 0.70702723+0.j        ,
       0.        -0.00026513j, 0.01060289+0.j        ])

In [7]:
executor.sample(
    qc,
    pop = [0.5, 0.6],
    p = [0.3,0.5],
    x = 0.1,
)


{'00': 4995, '01': 5003, '11': 2}

In [6]:
v = executor.expectation_value_derivatives(
    qc,
    operator,
    "pop",
    "p",
    "",
    "x",
    pop = [0.5, 0.6],
    p = [0.3,0.5],
    x = 0.1,
    )
print(v)

c:\Users\MOW-DK\dev\Executor\.venv\Lib\site-packages\qiskit\primitives\backend_estimator_v2.py:290: ComplexWarning: Casting complex values to real discards the imaginary part
  evs[index] += expval * coeff
c:\Users\MOW-DK\dev\Executor\.venv\Lib\site-packages\qiskit\primitives\backend_estimator_v2.py:290: ComplexWarning: Casting complex values to real discards the imaginary part
  evs[index] += expval * coeff


{'pop': np.float64(-0.0005249023437500014), 'p': np.float64(0.0), '': np.float64(-0.00311279296875)}


c:\Users\MOW-DK\dev\Executor\.venv\Lib\site-packages\qiskit\primitives\backend_estimator_v2.py:290: ComplexWarning: Casting complex values to real discards the imaginary part
  evs[index] += expval * coeff
